name: HolaMundo

on:
  push:
    branches:
      - aprendiendo-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - run: java HelloWorldApp.java
