name: triggers
run-name: triggers

permissions:
  issues: write
  pull-requests: write
  contents: read

on:
  issues:
    types: [opened, edited, closed]


jobs:
  triggers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr java con variable
        run: java HelloWorldApp2.java