name: triggers
run-name: triggers



on:
  workflow_dispatch:
    inputs:
    alerta:
      description: 'nivel'
      required: true
      default: alto
      type: choice
      options:
      - bajo
      - medio
      - alto

permissions:
  contents: write

jobs:
  triggers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr java con variable
        run: java HelloWorldApp2.java